import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const html = await readFile(new URL('../index.html', import.meta.url), 'utf8');
const styles = await readFile(new URL('../styles.css', import.meta.url), 'utf8');
const readme = await readFile(new URL('../README.md', import.meta.url), 'utf8');
const scorecard = await readFile(new URL('../WEBSITE-VENDOR-EVALUATION-SCORECARD.md', import.meta.url), 'utf8');
const aiSearchChecklist = await readFile(new URL('../AI-SEARCH-PROGRAM-RFP-REQUIREMENTS-CHECKLIST.md', import.meta.url), 'utf8');
const migrationEstimator = await readFile(new URL('../LARGE-WEBSITE-MIGRATION-SCOPE-ESTIMATOR.md', import.meta.url), 'utf8');
const buyerKit = await readFile(new URL('../WEBSITE-PROCUREMENT-BUYER-KIT.md', import.meta.url), 'utf8');
const operationsParity = await readFile(new URL('../SERVICE-WEBSITE-OPERATIONS-PARITY-CHECKLIST.md', import.meta.url), 'utf8');
const discoveryBookingCard = await readFile(new URL('../LOCAL-SERVICE-DISCOVERY-TO-BOOKING-MEASUREMENT-CARD.md', import.meta.url), 'utf8');
const capitalProjectUpdateBrief = await readFile(new URL('../CAPITAL-PROJECT-WEBSITE-UPDATE-BRIEF.md', import.meta.url), 'utf8');
const texasSolarHandoff = await readFile(new URL('../TEXAS-RESIDENTIAL-SOLAR-WEB-AND-SALES-HANDOFF-READINESS-CHECKLIST.md', import.meta.url), 'utf8');
const businessPitchProofCard = await readFile(new URL('../BUSINESS-PITCH-TO-WEBSITE-PROOF-CARD.md', import.meta.url), 'utf8');
const venueInquiryRoutingCard = await readFile(new URL('../VENUE-WEBSITE-INQUIRY-ROUTING-QA-CARD.md', import.meta.url), 'utf8');
const nonprofitSupporterHandoff = await readFile(new URL('../NONPROFIT-SUPPORTER-JOURNEY-HANDOFF-CHECKLIST.md', import.meta.url), 'utf8');
const restaurantEventOrderHandoff = await readFile(new URL('../RESTAURANT-EVENT-TO-ORDER-AND-CONTACT-HANDOFF-QA-CARD.md', import.meta.url), 'utf8');
const contactFormDeliveryVerification = await readFile(new URL('../WEBSITE-CONTACT-FORM-DELIVERY-VERIFICATION-CARD.md', import.meta.url), 'utf8');
const commercialContractorHandoff = await readFile(new URL('../COMMERCIAL-CONTRACTOR-CAPABILITY-TO-INQUIRY-HANDOFF-QA-CARD.md', import.meta.url), 'utf8');
const migrationTool = await readFile(new URL('../tools/migration-scope-estimator.mjs', import.meta.url), 'utf8');

assert.match(html, /<h1[^>]*>Make the hard decisions visible/);
assert.equal((html.match(/<link rel="canonical"/g) ?? []).length, 1);
assert.equal((html.match(/type="checkbox"/g) ?? []).length, 12);
assert.match(html, /utm_campaign=procurement_preflight/);
assert.match(html, /section508\.gov\/buy\//);
assert.match(html, /Excelsior_Springs_Website_RFP_2026\.pdf/);
assert.match(html, /27-05_rfp_economic-development-website-redesign\.pdf/);
assert.match(html, /Submission logistics and authority/);
assert.match(html, /contact click carries only the readiness band/);
assert.match(html, /data-consult/);
assert.match(html, /aria-live="polite"/);
assert.match(styles, /prefers-reduced-motion/);
assert.match(readme, /Website Vendor Evaluation Scorecard/);
assert.match(scorecard, /\| \*\*Total\*\* \| \*\*100\*\*/);
assert.match(scorecard, /factor points = weight × rating ÷ 5/);
assert.match(scorecard, /utm_campaign=website_vendor_scorecard/);
assert.match(scorecard, /section508\.gov\/buy\//);
assert.match(scorecard, /csrc\.nist\.gov\/pubs\/sp\/800\/218\/final/);
assert.match(readme, /AI Search Program RFP Requirements Checklist/);
assert.match(aiSearchChecklist, /OAI-SearchBot/);
assert.match(aiSearchChecklist, /no ranking, citation, or inclusion guarantee/);
assert.match(aiSearchChecklist, /txsmartbuy\.gov\/esbd\/754-TXST-2026-RFP-512-VPMkCom/);
assert.match(aiSearchChecklist, /utm_campaign=ai_search_rfp_checklist/);
assert.match(readme, /Large Website Migration Scope Estimator/);
assert.match(readme, /Website Procurement Buyer Kit/);
assert.match(readme, /Service Website Operations Parity Checklist/);
assert.match(readme, /Local Service Discovery-to-Booking Measurement Card/);
assert.match(readme, /Capital Project Website Update Brief/);
assert.match(readme, /Texas Residential Solar Web and Sales Handoff Readiness Checklist/);
assert.match(readme, /Business Pitch-to-Website Proof Card/);
assert.match(readme, /Venue Website Inquiry-Routing QA Card/);
assert.match(readme, /Nonprofit Supporter-Journey Handoff Checklist/);
assert.match(readme, /Restaurant Event-to-Order and Contact Handoff QA Card/);
assert.match(readme, /Website Contact-Form Delivery Verification Card/);
assert.match(readme, /Commercial Contractor Capability-to-Inquiry Handoff QA Card/);
assert.match(migrationEstimator, /full-population automated checks/);
assert.match(migrationEstimator, /utm_campaign=large_site_migration_estimator/);
assert.match(migrationEstimator, /developers\.google\.com\/search\/docs\/crawling-indexing\/site-move-with-url-changes/);
assert.match(migrationEstimator, /archives\.gov\/records-mgmt\/policy\/managing-web-records\.html/);
assert.match(migrationTool, /finitePopulationSample/);
assert.match(buyerKit, /## Pick the decision you need to make now/);
assert.match(buyerKit, /## Build one traceable evidence chain/);
assert.match(buyerKit, /## Run a response-readiness gate before release/);
assert.match(buyerKit, /mandatory response rows ready \/ mandatory response rows total/);
assert.match(buyerKit, /Eligibility and authority/);
assert.match(buyerKit, /References and permissions/);
assert.match(buyerKit, /Contract readiness/);
assert.match(buyerKit, /## Run the six-stage buying loop/);
assert.match(buyerKit, /WEBSITE-RFP-REQUIREMENTS-CHECKLIST\.md/);
assert.match(buyerKit, /WEBSITE-VENDOR-EVALUATION-SCORECARD\.md/);
assert.match(buyerKit, /AI-SEARCH-PROGRAM-RFP-REQUIREMENTS-CHECKLIST\.md/);
assert.match(buyerKit, /LARGE-WEBSITE-MIGRATION-SCOPE-ESTIMATOR\.md/);
assert.match(buyerKit, /acquisition\.gov\/far\/part-10/);
assert.match(buyerKit, /section508\.gov\/buy\//);
assert.match(buyerKit, /utm_campaign=website_procurement_buyer_kit/);
assert.match(operationsParity, /## Run the 12-field parity check/);
assert.match(operationsParity, /parity rate = matching applicable fields \/ applicable fields × 100/);
assert.match(operationsParity, /Do not label a booking-link click as a completed booking/);
assert.match(operationsParity, /developers\.google\.com\/search\/docs\/appearance\/structured-data\/local-business/);
assert.match(operationsParity, /w3\.org\/WAI\/tutorials\/forms\/instructions/);
assert.match(operationsParity, /utm_campaign=service_website_operations_parity_checklist/);
assert.match(discoveryBookingCard, /source-and-ownership map/i);
assert.match(discoveryBookingCard, /Do not call an outbound click a booking/);
assert.match(discoveryBookingCard, /Release with rollback evidence/);
assert.match(discoveryBookingCard, /utm_campaign=local_discovery_booking_handoff/);
assert.match(capitalProjectUpdateBrief, /Copy this public update/);
assert.match(capitalProjectUpdateBrief, /Update freshness:/);
assert.match(capitalProjectUpdateBrief, /utm_campaign=capital_project_update_brief/);
assert.match(html, /CAPITAL-PROJECT-WEBSITE-UPDATE-BRIEF\.md/);
assert.match(texasSolarHandoff, /Updated September 2, 2026/);
assert.match(texasSolarHandoff, /temporarily suspended until November 1, 2026/);
assert.match(texasSolarHandoff, /Do not infer that registration or other requirements are suspended/);
assert.match(texasSolarHandoff, /Run the 16-field fact and handoff check/);
assert.match(texasSolarHandoff, /Synthetic journeys passed \/ failed/);
assert.match(texasSolarHandoff, /not legal advice or a compliance certification/);
assert.match(texasSolarHandoff, /tdlr\.texas\.gov\/residential-solar-retailers\/effect\.htm/);
assert.match(texasSolarHandoff, /sos\.texas\.gov\/texreg\/archive\/June262026\/Adopted%20Rules\/16\.ECONOMIC%20REGULATION\.html/);
assert.match(texasSolarHandoff, /utm_campaign=texas_solar_web_sales_handoff/);
assert.match(businessPitchProofCard, /Claim parity rate = matching applicable claims \/ applicable claims x 100/);
assert.match(businessPitchProofCard, /Decision-path completion rate = passed applicable journey-device checks \/ applicable journey-device checks x 100/);
assert.match(businessPitchProofCard, /did not identify the finalists/);
assert.match(businessPitchProofCard, /utm_campaign=business_pitch_website_proof_card/);
assert.match(venueInquiryRoutingCard, /A populated album labeled "Coming Soon" fails/);
assert.match(venueInquiryRoutingCard, /venue-routing completeness = verified submissions carrying a venue value/);
assert.match(venueInquiryRoutingCard, /Do not claim that a website change caused revenue/);
assert.match(venueInquiryRoutingCard, /utm_campaign=venue_inquiry_routing_qa/);
assert.match(nonprofitSupporterHandoff, /Resolve material contradictions before adding promotion/);
assert.match(nonprofitSupporterHandoff, /Receipt integrity rate\*\* = internally received approved test submissions/);
assert.match(nonprofitSupporterHandoff, /Do not call a click a donation, registration, volunteer, application, or revenue outcome/);
assert.match(nonprofitSupporterHandoff, /utm_campaign=nonprofit_supporter_journey_handoff/);
assert.match(html, /NONPROFIT-SUPPORTER-JOURNEY-HANDOFF-CHECKLIST\.md/);
assert.match(restaurantEventOrderHandoff, /utm_campaign=restaurant_event_order_handoff/);
assert.match(restaurantEventOrderHandoff, /Provider acceptance and internal receipt are separate checks/);
assert.match(contactFormDeliveryVerification, /utm_campaign=contact_form_delivery_verification/);
assert.match(contactFormDeliveryVerification, /do not read, synthesize, solve, or bypass the challenge/i);
assert.match(contactFormDeliveryVerification, /Bound the submit and choose provider-specific proof/);
assert.match(contactFormDeliveryVerification, /semantic accepted status in the response body/);
assert.match(contactFormDeliveryVerification, /Do not retry until the organization can prove the first attempt was not accepted/);
assert.match(readme, /Featured form-delivery resource/);
assert.match(readme, /utm_campaign=contact_form_delivery_verification_feature/);
assert.match(html, /WEBSITE-CONTACT-FORM-DELIVERY-VERIFICATION-CARD\.md/);
assert.match(html, /COMMERCIAL-CONTRACTOR-CAPABILITY-TO-INQUIRY-HANDOFF-QA-CARD\.md/);
assert.match(commercialContractorHandoff, /Capability parity rate/);
assert.match(commercialContractorHandoff, /Provider acceptance and internal receipt are separate checks/);
assert.match(commercialContractorHandoff, /do not bypass it/i);
assert.match(commercialContractorHandoff, /utm_campaign=commercial_contractor_inquiry_handoff/);

const jsonLd = html.match(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/);
assert.ok(jsonLd, 'WebApplication structured data is present');
assert.equal(JSON.parse(jsonLd[1])['@type'], 'WebApplication');

console.log('Static checks passed.');






